//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wdfxekhach.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XUANCUONG-PC;Initial Catalog=QL_BANVEXEKHACH;Integrated Security=True" +
            ";TrustServerCertificate=True")]
        public string QL_BANVEXEKHACHConnectionString {
            get {
                return ((string)(this["QL_BANVEXEKHACHConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XUANCUONG-PC;Initial Catalog=databaseQLBanVeXeKhach;Integrated Securi" +
            "ty=True;TrustServerCertificate=True")]
        public string databaseQLBanVeXeKhachConnectionString {
            get {
                return ((string)(this["databaseQLBanVeXeKhachConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XUANCUONG-PC;Initial Catalog=quanlyxekhachdoan;Integrated Security=Tr" +
            "ue;TrustServerCertificate=True")]
        public string quanlyxekhachdoanConnectionString {
            get {
                return ((string)(this["quanlyxekhachdoanConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XUANCUONG-PC;Initial Catalog=QuanLyVeXeKhach_NET;Integrated Security=" +
            "True;TrustServerCertificate=True")]
        public string QuanLyVeXeKhach_NETConnectionString {
            get {
                return ((string)(this["QuanLyVeXeKhach_NETConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XUANCUONG-PC;Initial Catalog=QL_BANVEXEKHACH_NET;Integrated Security=" +
            "True;TrustServerCertificate=True")]
        public string QL_BANVEXEKHACH_NETConnectionString {
            get {
                return ((string)(this["QL_BANVEXEKHACH_NETConnectionString"]));
            }
        }
    }
}
