//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wdfxekhach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class databaseQLBanVeXeKhachEntities : DbContext
    {
        public databaseQLBanVeXeKhachEntities()
            : base("name=databaseQLBanVeXeKhachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETVEXE> CHITIETVEXE { get; set; }
        public virtual DbSet<CHUYENXE> CHUYENXE { get; set; }
        public virtual DbSet<HANHKHACH> HANHKHACH { get; set; }
        public virtual DbSet<LOAIXE> LOAIXE { get; set; }
        public virtual DbSet<PHANCONG_TAIXE_CHUYENXE> PHANCONG_TAIXE_CHUYENXE { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public virtual DbSet<TAIXE> TAIXE { get; set; }
        public virtual DbSet<TINHTHANH> TINHTHANH { get; set; }
        public virtual DbSet<TUYENXE> TUYENXE { get; set; }
        public virtual DbSet<VEXE> VEXE { get; set; }
        public virtual DbSet<XE> XE { get; set; }
    }
}
