//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wdfxekhach
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETVEXE
    {
        public int MaNhanVien { get; set; }
        public int MaVeXe { get; set; }
        public string DiemDon { get; set; }
        public string DiemTra { get; set; }
        public System.DateTime NgayXuat { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual VEXE VEXE { get; set; }
    }
}
