//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wdfxekhach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_BANVEXEKHACH_NETEntities1 : DbContext
    {
        public QL_BANVEXEKHACH_NETEntities1()
            : base("name=QL_BANVEXEKHACH_NETEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETVEXE> CHITIETVEXEs { get; set; }
        public virtual DbSet<CHUYENXE> CHUYENXEs { get; set; }
        public virtual DbSet<HANHKHACH> HANHKHACHes { get; set; }
        public virtual DbSet<LOAIXE> LOAIXEs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<TAIXE> TAIXEs { get; set; }
        public virtual DbSet<TINHTHANH> TINHTHANHs { get; set; }
        public virtual DbSet<TUYENXE> TUYENXEs { get; set; }
        public virtual DbSet<VEXE> VEXEs { get; set; }
        public virtual DbSet<XE> XEs { get; set; }
    
        public virtual ObjectResult<LayTTNhanVien_Result> LayTTNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayTTNhanVien_Result>("LayTTNhanVien");
        }
    }
}
