//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wdfxekhach
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUYENXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUYENXE()
        {
            this.CHUYENXEs = new HashSet<CHUYENXE>();
        }
    
        public int MaTuyenXe { get; set; }
        public string TenTuyenXe { get; set; }
        public int DiemDi { get; set; }
        public int DiemDen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENXE> CHUYENXEs { get; set; }
        public virtual TINHTHANH TINHTHANH { get; set; }
        public virtual TINHTHANH TINHTHANH1 { get; set; }
    }
}
