//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wdfxekhach
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEXE
    {
        public int MaVeXe { get; set; }
        public int MaHanhKhach { get; set; }
        public int MaChuyenXe { get; set; }
        public int SoGhe { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual CHITIETVEXE CHITIETVEXE { get; set; }
        public virtual CHUYENXE CHUYENXE { get; set; }
        public virtual HANHKHACH HANHKHACH { get; set; }
    }
}
